//package Advanced_Java_Projects.JavaF;
//
//
///*
// * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
// * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
// */
//
///**
// *
// * @author wasif
// */
//public class NewJPanelDemo extends javax.swing.JPanel {
//
//    public static void main(String[] args) {
//        NewJPanelDemo();
//    }
//
//    /**
//     * Creates new form NewJPanelDemo
//     */
//    public NewJPanelDemo() {
//        initComponents();
//    }
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">
//    public void initComponents() {
//
//        jColorChooser1 = new javax.swing.JColorChooser();
//        jColorChooser2 = new javax.swing.JColorChooser();
//        jLabel1 = new javax.swing.JLabel();
//        jLabel2 = new javax.swing.JLabel();
//        jLabel3 = new javax.swing.JLabel();
//        jButton1 = new javax.swing.JButton();
//        jLabel4 = new javax.swing.JLabel();
//        jTextField1 = new javax.swing.JTextField();
//        jLabel5 = new javax.swing.JLabel();
//        jLabel6 = new javax.swing.JLabel();
//
//        jLabel1.setText("jLabel1");
//
//        jLabel2.setText("jLabel2");
//
//        jLabel3.setText("+");
//
//        jButton1.setText("jButton1");
//
//        jLabel4.setText("=");
//
//        jTextField1.setText("jTextField1");
//        jTextField1.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jTextField1ActionPerformed(evt);
//            }
//        });
//
//        jLabel5.setText("Timer:");
//
//        jLabel6.setText("Score:");
//
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
//        this.setLayout(layout);
//        layout.setHorizontalGroup(
//                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(layout.createSequentialGroup()
//                                .addGap(76, 76, 76)
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//                                        .addComponent(jButton1)
//                                        .addGroup(layout.createSequentialGroup()
//                                                .addComponent(jLabel1)
//                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                                .addComponent(jLabel3)
//                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                                .addComponent(jLabel2)
//                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                                .addComponent(jLabel4)
//                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//                                                                .addComponent(jLabel6)
//                                                                .addComponent(jLabel5)))))
//                                .addContainerGap(135, Short.MAX_VALUE))
//        );
//        layout.setVerticalGroup(
//                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(layout.createSequentialGroup()
//                                .addGap(77, 77, 77)
//                                .addComponent(jLabel6)
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                .addComponent(jLabel5)
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                        .addComponent(jLabel1)
//                                        .addComponent(jLabel2)
//                                        .addComponent(jLabel3)
//                                        .addComponent(jLabel4)
//                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                .addComponent(jButton1)
//                                .addContainerGap(128, Short.MAX_VALUE))
//        );
//    }// </editor-fold>
//
//    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
//
//
//
//    }
//
//
//    // Variables declaration - do not modify
//    private javax.swing.JButton jButton1;
//    private javax.swing.JColorChooser jColorChooser1;
//    private javax.swing.JColorChooser jColorChooser2;
//    private javax.swing.JLabel jLabel1;
//    private javax.swing.JLabel jLabel2;
//    private javax.swing.JLabel jLabel3;
//    private javax.swing.JLabel jLabel4;
//    private javax.swing.JLabel jLabel5;
//    private javax.swing.JLabel jLabel6;
//    private javax.swing.JTextField jTextField1;
//    // End of variables declaration
//}
